<a href="https://colab.research.google.com/github/SereneSorceress/20241cai0223-NVIDIA-INTERNSHIP/blob/main/fashion_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print("Tensor flow version:",tf.__version__)
print("GPU Avilable:")
tf.config.list_physical_devices('GPU')

Tensor flow version: 2.20.0
GPU Avilable:


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

In [ ]:
fashion_mnist = tf.keras.datasets.fashion_mnist
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()
print("Training Data Shape:&quot", X_train.shape)
print("Testing Data Shape:", X_test.shape)

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Training Data Shape:&quot (60000, 28, 28)
Testing Data Shape: (10000, 28, 28)


In [ ]:
X_train = X_train / 255.0
X_test = X_test / 255.0

In [ ]:
model = tf.keras.Sequential([
    tf.keras.Input(shape=(28, 28)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [ ]:
model.compile(
optimizer='adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy']

)

In [ ]:
history = model.fit(
X_train,
y_train,
epochs=10,
batch_size=128,
validation_split=0.2
)

Epoch 1/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7730 - loss: 0.6305 - val_accuracy: 0.8390 - val_loss: 0.4339
Epoch 2/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8451 - loss: 0.4252 - val_accuracy: 0.8580 - val_loss: 0.3859
Epoch 3/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8572 - loss: 0.3839 - val_accuracy: 0.8661 - val_loss: 0.3761
Epoch 4/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8702 - loss: 0.3543 - val_accuracy: 0.8746 - val_loss: 0.3435
Epoch 5/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8736 - loss: 0.3413 - val_accuracy: 0.8766 - val_loss: 0.3375
Epoch 6/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8788 - loss: 0.3232 - val_accuracy: 0.8832 - val_loss: 0.3309
Epoch 7/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8844 - loss: 0.3099 - val_accuracy: 0.8808 - val_loss: 0.3258
Epoch 8/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8858 - loss: 0.3048 - val_accuracy: 0.

In [ ]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("\nTest Accuracy:", test_accuracy)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8793 - loss: 0.3361

Test Accuracy: 0.8792999982833862


In [ ]:
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [ ]:
print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_classes))


Confusion Matrix
[[871   1  22  23   3   0  71   0   9   0]
 [  4 964   1  24   3   0   3   0   1   0]
 [ 14   1 851  12  60   0  61   0   1   0]
 [ 27   4  13 901  32   0  20   0   3   0]
 [  0   0 172  32 745   0  50   0   1   0]
 [  0   0   0   0   0 966   0  26   1   7]
 [167   0 106  29  63   0 623   0  12   0]
 [  0   0   0   0   0  12   0 959   0  29]
 [  5   0   3   5   6   3  11   8 959   0]
 [  0   0   0   0   0  12   1  33   0 954]]


In [ ]:
print("\nClassification Report")
print(classification_report(y_test, y_pred_classes))


Classification Report
              precision    recall  f1-score   support

           0       0.80      0.87      0.83      1000
           1       0.99      0.96      0.98      1000
           2       0.73      0.85      0.79      1000
           3       0.88      0.90      0.89      1000
           4       0.82      0.74      0.78      1000
           5       0.97      0.97      0.97      1000
           6       0.74      0.62      0.68      1000
           7       0.93      0.96      0.95      1000
           8       0.97      0.96      0.97      1000
           9       0.96      0.95      0.96      1000

    accuracy                           0.88     10000
   macro avg       0.88      0.88      0.88     10000
weighted avg       0.88      0.88      0.88     10000

